In [1]:
import pandas as pd

In [30]:
df = pd.read_csv("C:\\Users\\anish\Desktop\\Project Practicum\\CUB_200_2011\\CUB_200_2011\\attributes\\image_attribute_labels.txt", header=None, sep=' ', names=['Image_id','Attribute_id','Is_present','Certainities','tp','tp1','tp2'])

In [32]:
df.tail(10)

         Image_id  Attribute_id  Is_present  Certainities     tp  tp1  tp2
3677846     11788           303           0             4  4.989  NaN  NaN
3677847     11788           304           0             4  4.989  NaN  NaN
3677848     11788           305           0             4  4.989  NaN  NaN
3677849     11788           306           1             4  4.989  NaN  NaN
3677850     11788           307           0             4  4.989  NaN  NaN
3677851     11788           308           1             4  4.989  NaN  NaN
3677852     11788           309           0             4  8.309  NaN  NaN
3677853     11788           310           0             4  8.309  NaN  NaN
3677854     11788           311           0             4  8.309  NaN  NaN
3677855     11788           312           1             4  8.309  NaN  NaN

In [41]:
df_image_attribute_labels = df.loc[:,['Image_id','Attribute_id','Is_present']]

In [42]:
df_image_attribute_labels.shape

(3677856, 3)

In [43]:
df_image_attribute_labels.head(10)

   Image_id  Attribute_id  Is_present
0         1             1           0
1         1             2           0
2         1             3           0
3         1             4           0
4         1             5           1
5         1             6           0
6         1             7           0
7         1             8           0
8         1             9           0
9         1            10           0

In [47]:
df_attributes = pd.read_csv("C:\\Users\\anish\\Desktop\\Project Practicum\\CUB_200_2011\\attributes.txt",header=None,sep=' ',names=['Attribute_id','Attribute'])

In [108]:
df_attributes

     Attribute_id                            Attribute
0               1  has_bill_shape::curved_(up_or_down)
1               2               has_bill_shape::dagger
2               3               has_bill_shape::hooked
3               4               has_bill_shape::needle
4               5       has_bill_shape::hooked_seabird
..            ...                                  ...
307           308                has_crown_color::buff
308           309              has_wing_pattern::solid
309           310            has_wing_pattern::spotted
310           311            has_wing_pattern::striped
311           312      has_wing_pattern::multi-colored

[312 rows x 2 columns]

In [117]:
df_attributes.shape

(312, 2)

In [49]:
df_images = pd.read_csv("C:\\Users\\anish\\Desktop\\Project Practicum\\CUB_200_2011\\CUB_200_2011\\images.txt", sep=' ', header=None, names=['Image_id','Image_name'])

In [210]:
df_images.head(10)

   Image_id                                         Image_name
0         1  001.Black_footed_Albatross/Black_Footed_Albatr...
1         2  001.Black_footed_Albatross/Black_Footed_Albatr...
2         3  001.Black_footed_Albatross/Black_Footed_Albatr...
3         4  001.Black_footed_Albatross/Black_Footed_Albatr...
4         5  001.Black_footed_Albatross/Black_Footed_Albatr...
5         6  001.Black_footed_Albatross/Black_Footed_Albatr...
6         7  001.Black_footed_Albatross/Black_Footed_Albatr...
7         8  001.Black_footed_Albatross/Black_Footed_Albatr...
8         9  001.Black_footed_Albatross/Black_Footed_Albatr...
9        10  001.Black_footed_Albatross/Black_Footed_Albatr...

In [211]:
df_images['After Split'] = df_images['Image_name'].str.split('/')

In [224]:
df_images['Image'] = df_images['After Split'].str[1]

In [231]:
del df_images['After Split']
del df_images['Test']
del df_images['Image_name']

In [232]:
df_images

       Image_id                                Image
0             1   Black_Footed_Albatross_0046_18.jpg
1             2   Black_Footed_Albatross_0009_34.jpg
2             3   Black_Footed_Albatross_0002_55.jpg
3             4   Black_Footed_Albatross_0074_59.jpg
4             5   Black_Footed_Albatross_0014_89.jpg
...         ...                                  ...
11783     11784  Common_Yellowthroat_0037_190698.jpg
11784     11785  Common_Yellowthroat_0058_190958.jpg
11785     11786  Common_Yellowthroat_0008_190703.jpg
11786     11787  Common_Yellowthroat_0049_190708.jpg
11787     11788  Common_Yellowthroat_0055_190967.jpg

[11788 rows x 2 columns]

In [233]:
df_res_img = pd.merge(df_image_attribute_labels, df_images[['Image_id','Image']], on='Image_id')

In [234]:
df_res_img.head(10)

   Image_id  Attribute_id  Is_present                               Image
0         1             1           0  Black_Footed_Albatross_0046_18.jpg
1         1             2           0  Black_Footed_Albatross_0046_18.jpg
2         1             3           0  Black_Footed_Albatross_0046_18.jpg
3         1             4           0  Black_Footed_Albatross_0046_18.jpg
4         1             5           1  Black_Footed_Albatross_0046_18.jpg
5         1             6           0  Black_Footed_Albatross_0046_18.jpg
6         1             7           0  Black_Footed_Albatross_0046_18.jpg
7         1             8           0  Black_Footed_Albatross_0046_18.jpg
8         1             9           0  Black_Footed_Albatross_0046_18.jpg
9         1            10           0  Black_Footed_Albatross_0046_18.jpg

In [235]:
df_res_img.shape

(3677856, 4)

In [239]:
df_res_img.loc[df_res_img['Image_id']==1223,['Image']]

                                   Image
381264  Chuck_Will_Widow_0041_796997.jpg
381265  Chuck_Will_Widow_0041_796997.jpg
381266  Chuck_Will_Widow_0041_796997.jpg
381267  Chuck_Will_Widow_0041_796997.jpg
381268  Chuck_Will_Widow_0041_796997.jpg
...                                  ...
381571  Chuck_Will_Widow_0041_796997.jpg
381572  Chuck_Will_Widow_0041_796997.jpg
381573  Chuck_Will_Widow_0041_796997.jpg
381574  Chuck_Will_Widow_0041_796997.jpg
381575  Chuck_Will_Widow_0041_796997.jpg

[312 rows x 1 columns]

In [128]:
df_res_attr = pd.merge(df_image_attribute_labels, df_attributes[['Attribute_id','Attribute']], on='Attribute_id')

In [129]:
df_res_attr.iloc[55522]

Image_id                                  8371
Attribute_id                                 5
Is_present                                   0
Attribute       has_bill_shape::hooked_seabird
Name: 55522, dtype: object

In [130]:
df_res_attr.head(10)

   Image_id  Attribute_id  Is_present                            Attribute
0         1             1           0  has_bill_shape::curved_(up_or_down)
1         2             1           0  has_bill_shape::curved_(up_or_down)
2         3             1           0  has_bill_shape::curved_(up_or_down)
3         4             1           0  has_bill_shape::curved_(up_or_down)
4         5             1           0  has_bill_shape::curved_(up_or_down)
5         6             1           0  has_bill_shape::curved_(up_or_down)
6         7             1           0  has_bill_shape::curved_(up_or_down)
7         8             1           0  has_bill_shape::curved_(up_or_down)
8         9             1           0  has_bill_shape::curved_(up_or_down)
9        10             1           0  has_bill_shape::curved_(up_or_down)

In [135]:
df_res_attr.loc[df_res_attr['Image_id']==6]

,Image_id,Attribute_id,Is_present,Attribute
5,6,1,0,has_bill_shape::curved_(up_or_down)
11793,6,2,0,has_bill_shape::dagger
23581,6,3,0,has_bill_shape::hooked
35369,6,4,0,has_bill_shape::needle
47157,6,5,1,has_bill_shape::hooked_seabird
...,...,...,...,...
3618921,6,308,1,has_crown_color::buff
3630709,6,309,0,has_wing_pattern::solid
3642497,6,310,1,has_wing_pattern::spotted
3654285,6,311,0,has_wing_pattern::striped
3666073,6,312,0,has_wing_pattern::multi-colored

In [240]:
df_final = pd.merge(df_res_img,df_attributes[['Attribute_id','Attribute']], on='Attribute_id')

In [247]:
df_final.shape

(3677856, 5)

In [248]:
df_final.loc[df_final['Image_id']==777]

,Image_id,Attribute_id,Is_present,Image,Attribute
776,777,1,0,Indigo_Bunting_0031_13300.jpg,has_bill_shape::curved_(up_or_down)
12564,777,2,0,Indigo_Bunting_0031_13300.jpg,has_bill_shape::dagger
24352,777,3,0,Indigo_Bunting_0031_13300.jpg,has_bill_shape::hooked
36140,777,4,0,Indigo_Bunting_0031_13300.jpg,has_bill_shape::needle
47928,777,5,0,Indigo_Bunting_0031_13300.jpg,has_bill_shape::hooked_seabird
...,...,...,...,...,...
3619692,777,308,0,Indigo_Bunting_0031_13300.jpg,has_crown_color::buff
3631480,777,309,0,Indigo_Bunting_0031_13300.jpg,has_wing_pattern::solid
3643268,777,310,1,Indigo_Bunting_0031_13300.jpg,has_wing_pattern::spotted
3655056,777,311,0,Indigo_Bunting_0031_13300.jpg,has_wing_pattern::striped
3666844,777,312,0,Indigo_Bunting_0031_13300.jpg,has_wing_pattern::multi-colored

In [249]:
df_final.loc[df_final['Is_present']==0,'Is_present']=-1

In [250]:
df_final.head(10)

,Image_id,Attribute_id,Is_present,Image,Attribute
0,1,1,-1,Black_Footed_Albatross_0046_18.jpg,has_bill_shape::curved_(up_or_down)
1,2,1,-1,Black_Footed_Albatross_0009_34.jpg,has_bill_shape::curved_(up_or_down)
2,3,1,-1,Black_Footed_Albatross_0002_55.jpg,has_bill_shape::curved_(up_or_down)
3,4,1,-1,Black_Footed_Albatross_0074_59.jpg,has_bill_shape::curved_(up_or_down)
4,5,1,-1,Black_Footed_Albatross_0014_89.jpg,has_bill_shape::curved_(up_or_down)
5,6,1,-1,Black_Footed_Albatross_0085_92.jpg,has_bill_shape::curved_(up_or_down)
6,7,1,-1,Black_Footed_Albatross_0031_100.jpg,has_bill_shape::curved_(up_or_down)
7,8,1,-1,Black_Footed_Albatross_0051_796103.jpg,has_bill_shape::curved_(up_or_down)
8,9,1,-1,Black_Footed_Albatross_0010_796097.jpg,has_bill_shape::curved_(up_or_down)
9,10,1,-1,Black_Footed_Albatross_0025_796057.jpg,has_bill_shape::curved_(up_or_down)

In [251]:
pivoted = df_final.pivot(index='Image', columns="Attribute",values='Is_present')

In [252]:
pivoted

Attribute,has_back_color::black,has_back_color::blue,has_back_color::brown,has_back_color::buff,has_back_color::green,has_back_color::grey,has_back_color::iridescent,has_back_color::olive,has_back_color::orange,has_back_color::pink,...,has_wing_color::yellow,has_wing_pattern::multi-colored,has_wing_pattern::solid,has_wing_pattern::spotted,has_wing_pattern::striped,has_wing_shape::broad-wings,has_wing_shape::long-wings,has_wing_shape::pointed-wings,has_wing_shape::rounded-wings,has_wing_shape::tapered-wings
Image,,,,,,,,,,,,,,,,,,,,,
Acadian_Flycatcher_0003_29094.jpg,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,1,-1,-1,1,-1,-1
Acadian_Flycatcher_0004_795623.jpg,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,1,-1,-1,-1,-1,-1,-1,-1,-1
Acadian_Flycatcher_0005_29157.jpg,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
Acadian_Flycatcher_0006_795595.jpg,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
Acadian_Flycatcher_0007_795600.jpg,-1,-1,-1,1,-1,1,-1,-1,-1,-1,...,-1,-1,-1,-1,1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yellow_Warbler_0118_176409.jpg,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,-1,-1,-1,-1,-1,-1,-1,-1,-1
Yellow_Warbler_0119_176485.jpg,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
Yellow_Warbler_0121_176402.jpg,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,-1,-1,-1,1,-1,-1,-1,-1,-1
Yellow_Warbler_0122_176182.jpg,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,-1,-1,-1,-1,-1,-1,1,-1
Yellow_Warbler_0123_176471.jpg,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,-1,-1,-1,1,-1,-1,1,-1,-1

In [253]:
pivoted.to_csv('C:\\Users\\anish\\Desktop\\annoCUB.csv', sep=' ')

In [254]:
pivoted.to_csv('C:\\Users\\anish\\Desktop\\test.txt',sep=' ')

In [209]:
import glob
from shutil import copy
dir_src = r"C:/Users/anish/Desktop/Project Practicum/CUB_200_2011/CUB_200_2011/images"
dir_dst = r"C:/Users/anish/Desktop/CUB200_Train"
for file in glob.iglob('%s/**/*.jpg' % dir_src, recursive=True):
    copy(file, dir_dst)